### ISSUE TITLE
Performance: Logging pruned release builds

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/diamond-node#156]
It is possible to not even include the ressource intensive log preparations into the binary, by configuring builds to not include low level logs in the binary. More about: https://docs.rs/log/latest/log/index.html

For example, a crate can disable trace level logs in debug builds and trace, debug, and info level logs in release builds with the following configuration:
```toml
[dependencies]
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
```
